// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Add(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AllData():Promise<Array<backend.UserData>>;

export function Delete(arg1:string):Promise<string>;

export function Edit(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Generate(arg1:number):Promise<string>;

export function PasswordProtect():Promise<string>;

export function Search(arg1:string):Promise<Array<any>>;
